nexus:
  build: ./nexus
  ports:
    - "18081:8081"

jenkins:
  build: ./jenkins
  ports:
    - "18080:8080"
  links:
    - nexus:nexus
    - sonar:sonar
    - selhub:hub
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/local/bin/docker:/usr/bin/docker

sonar:
  build: ./sonar
  ports:
   - "19000:9000"
   - "5432:5432"
  environment:
   - SONARQUBE_JDBC_URL=jdbc:postgresql://localhost:5432/sonar
db:
  image: postgres
  net: container:sonar
  environment:
   - POSTGRES_USER=sonar
   - POSTGRES_PASSWORD=sonar

selhub:
  image: selenium/hub
  ports:
    - 4444:4444

nodeff:
  image: selenium/node-firefox-debug
  ports:
    - 5900
  links:
    - selhub:hub

nodechrome:
  image: selenium/node-chrome-debug
  ports:
    - 5900
  links:
    - selhub:hub
