version: '2'
services:
 nexus:
  build: ./nexus
  ports:
    - "18081:8081"

 jenkins:
  build: ./jenkins
  ports:
    - "18080:8080"
  links:
    - nexus:nexus
    - gitlab:gitlab
    - sonar:sonar
    - selhub:hub
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/local/bin/docker:/usr/bin/docker
  depends_on:
    - nexus
    - gitlab
    - sonar
    - selhub
  environment:
    - NEXUS_PORT=8081
    - SONAR_PORT=9000
    - SONAR_DB_PORT=5432

 sonar:
  build: ./sonar
  ports:
   - "19000:9000"
   - "5432:5432"
  environment:
   - SONARQUBE_JDBC_URL=jdbc:postgresql://localhost:5432/sonar
 db:
  network_mode: service:sonar
  image: postgres
  environment:
   - POSTGRES_USER=sonar
   - POSTGRES_PASSWORD=sonar

 selhub:
  image: selenium/hub
  ports:
    - 4444:4444

 nodeff:
  image: selenium/node-firefox-debug
  ports:
    - 5900
  links:
   - selhub:hub
  environment:
   - HUB_PORT_4444_TCP_ADDR=hub
  depends_on:
    - selhub

 nodechrome:
  image: selenium/node-chrome-debug
  ports:
    - 5900
  links:
   - selhub:hub
  environment:
   - HUB_PORT_4444_TCP_ADDR=hub
  depends_on:
    - selhub

 db2:
  image: postgres
  environment:
    - POSTGRES_USER=gitlab
    - POSTGRES_PASSWORD=gitlab
    - POSTGRES_DB=gitlab
 gitlab:
  image: sameersbn/gitlab:8.3.2
  links:
    - redis:redisio
    - db2:db2
  ports:
    - "10080:80"
    - "10022:22"
  depends_on:
    - db2
    - redis
  environment:
    - DB_HOST=db2
    - DB_NAME=gitlab
    - DB_USER=gitlab
    - DB_PASS=gitlab
    - REDIS_HOST=redisio

    - TZ=Europe/Madrid
    - GITLAB_TIMEZONE=Madrid

    - GITLAB_SECRETS_DB_KEY_BASE=long-and-random-alphanumeric-string

    - GITLAB_HOST=localhost
    - GITLAB_PORT=10080
    - GITLAB_SSH_PORT=10022

    - GITLAB_NOTIFY_ON_BROKEN_BUILDS=true
    - GITLAB_NOTIFY_PUSHER=false

    - GITLAB_EMAIL=notifications@example.com
    - GITLAB_EMAIL_REPLY_TO=noreply@example.com
    - GITLAB_INCOMING_EMAIL_ADDRESS=reply@example.com

    - GITLAB_BACKUPS=daily
    - GITLAB_BACKUP_TIME=01:00

    - SMTP_ENABLED=false
    - SMTP_DOMAIN=www.example.com
    - SMTP_HOST=smtp.gmail.com
    - SMTP_PORT=587
    - SMTP_USER=mailer@example.com
    - SMTP_PASS=password
    - SMTP_STARTTLS=true
    - SMTP_AUTHENTICATION=login

    - IMAP_ENABLED=false
    - IMAP_HOST=imap.gmail.com
    - IMAP_PORT=993
    - IMAP_USER=mailer@example.com
    - IMAP_PASS=password
    - IMAP_SSL=true
    - IMAP_STARTTLS=false
  volumes:
    - /srv/docker/gitlab/gitlab:/home/git/data
 redis:
  image: sameersbn/redis:latest
  volumes:
    - /srv/docker/gitlab/redis:/var/lib/redis
